[project]
name = "py4xl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=25.1.0",
    "excelize>=0.0.5",
    "fastexcel>=0.16.0",
    "jupyter>=1.1.1",
    "lxml>=6.0.1",
    "matplotlib>=3.10.3",
    "nltk>=3.9.1",
    "openpyxl>=3.1.3",
    "pandas==3.0.0rc0",
    "plotly>=6.2.0",
    "pyarrow>=22.0.0",
    "python-calamine>=0.5.3",
    "pyxlsb>=1.0.10",
    "ruff>=0.11.13",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.43",
    "ty>=0.0.1a17",
    "wordcloud>=1.9.4",
    "xlrd>=2.0.2",
    "xlsxwriter>=3.2.9",
    "xlutils>=2.0.0",
    "xlwings>=0.33.15",
    "xlwt>=1.3.0",
]
